### PR TITLE
feat(Button, Header): Add Button and Header common components

### PR DESCRIPTION
**Pull request by selynna**
Closes Button #6 and Header #7

### CODE REVIEW

**Comment by Jumer-Caragay** [comment]
`const border = "3px solid" + color;`
When you're adding the border does it need a space in front of solid?

**Comment by selynna** [comment]
@Jumer-Caragay good catch - fixed

**Comment by Jumer-Caragay** [comment]
@selynna In your Button and Header component  why did you destructure children from props when you didn't use it in your return?

**Review by Jumer-Caragay — APPROVED** [review]
Looks good

**Pull request merged**
